name = "doordash-scraper-api"
main = "src/api/index.ts"
compatibility_date = "2024-02-14"

[[d1_databases]]
binding = "DB"
database_name = "scraper-db"
database_id = "02adafc0-d13d-48a4-a474-0698781b50dc"
preview_database_id = "DB"
migrations_dir = "migrations"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["src/api/dist/assets/*.js"]
fallthrough = true

[[rules]]
type = "Text"
globs = ["src/api/dist/assets/*.css"]
fallthrough = false
